### ISSUE TITLE
Theme Issues for Danny

### ISSUE THREAD

**Issue by kehh** [wamuseum/providence#101]
Taken from https://github.com/wamuseum/providence/pull/98
- [x] Should we pull in the non CDN provided resources locally?
- [x] Dashboard still vanilla aside from going fullwidth
  ![dashboardvanilla](https://cloud.githubusercontent.com/assets/12571/3975477/c293a0a6-2809-11e4-9081-88dff54fc1d4.png)
- [x] Dashboard widgets narrow
  ![dashboardwidgetsnotfullwidth](https://cloud.githubusercontent.com/assets/12571/3975475/be64d5b8-2809-11e4-8c6a-f5ba3926db9d.png)
- [x] Login screen still vanilla
- [x] `_suckerfish.scss` is completely commented out
- [x] Browse facets - Find > Objects > Browse > By Entity
  - [x] Groupings are blue
    ![browsefacetsblue](https://cloud.githubusercontent.com/assets/12571/3975481/fe4cd0cc-2809-11e4-860f-506411467329.png)
  - [x] Groupings have strange float
- [x] Required fields not highlighted - these have a `<span class="required">*</span>`
- [x] only `:last-child` Links in the _New_ menu should be clickable. Probably just change the href to an anonymous anchor on the current page.

**Comment by kehh** [comment]
Found another issue
- [x] Browse facets seem to be larger and different styling once a facet has been chosen
  Before Specifying Type Facet:
  ![browsebeforespecifyingtype](https://cloud.githubusercontent.com/assets/12571/3990782/fb21c596-28d2-11e4-84d1-78bb4c3f7171.png)

After Specifying Type Facet:
![browseafterspecifyingtype](https://cloud.githubusercontent.com/assets/12571/3990789/1f09f028-28d3-11e4-9540-cbcd6bbf6bbc.png)

**Comment by DannyMurphy** [comment]
Thanks @kehh keep them coming

**Comment by kehh** [comment]
- [x] Media Representations look a bit iffy - Media tab on 'Arachnology' record
  ![media represenations](https://cloud.githubusercontent.com/assets/12571/3992090/26cb2e16-28f2-11e4-817f-367d70dea221.png)

**Comment by leftclickben** [comment]
Sorry, I initially put this in the wrong place.

> Should we pull in the non CDN provided resources locally?

Yes we definitely should :-) Otherwise we are needlessly introducing a cross-system dependency between the CMIS and the Museum website.

Another option is a separate, cookieless domain for these types of assets, which can be locked down so that URLs never change, and shared between any other projects. That way the dependency is only ever on that static domain, not between unrelated websites/apps. But that's a project in itself.

**Comment by DannyMurphy** [comment]
I think all of these are done now. Need to merge them form my repo

**Comment by kehh** [comment]
OK can you set up a PR for it?

**Comment by leftclickben** [comment]
Kehan stop working you're on leave!!! :-)

**Comment by DannyMurphy** [comment]
Done
