### ISSUE TITLE
Some admin screens have a broken layout

### ISSUE THREAD

**Issue by leftclickben** [wamuseum/providence#127]
For example, Manage > Access Control > User Logins as shown in attached image.
![admin-user-login-broken-layout](https://cloud.githubusercontent.com/assets/94266/4501721/4f16f0ac-4ab3-11e4-9bf2-27a1eff739fd.png)

**Comment by leftclickben** [comment]
Something just needs to be `clear`ed I'm guessing.

**Comment by DannyMurphy** [comment]
What browser are you using?

looks fine to me on staging and prod

**Comment by kehh** [comment]
I believe that's in Firefox.

**Comment by DannyMurphy** [comment]
Cheers
