### ISSUE TITLE
How to add JS file

### ISSUE THREAD

**Issue by DannyMurphy** [wamuseum/providence#130]
Hi @leftclickben & @kehh 

I have created a JS function I need to add to the page.

I currently have added JS file in the theme folder, but I am just trying to figure out how I add the javascript file to the head. I cannot figure out where the config file is to add another JS file

themes/views/pageFormat/pageHeader.php
67 `<?php`
68  `print JavascriptLoadManager::getLoadHTML($this->request->getBaseUrlPath());`
69  `print MetaTagManager::getHTML();`

Or 

is the local.js file a file created by you guys which I could just add my function to the bottom.

**Comment by leftclickben** [comment]
Hey Danny, 

The local.js is our file, it's loaded on every page afaik, so you can add your function(s) to it. 

Ben 

On 7 October 2014 9:59:38 AM AWST, Danny Murphy notifications@github.com wrote:

> Hi @leftclickben & @kehh 
> 
> I have created a JS function I need to add to the page.
> 
> I currently have added JS file in the theme folder, but I am just
> trying to figure out how I add the javascript file to the head. I
> cannot figure out where the config file is to add another JS file
> 
> themes/views/pageFormat/pageHeader.php
> 67 `<?php`
> 68 `print
> JavascriptLoadManager::getLoadHTML($this->request->getBaseUrlPath());`
> 69 `print MetaTagManager::getHTML();`
> 
> Or 
> 
> is the local.js file a file created by you guys which I could just add
> my function to the bottom.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/wamuseum/providence/issues/130

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by DannyMurphy** [comment]
Brill,

I am looking at those other issues as well.
