### ISSUE TITLE
Responsive image fix hides map tiles

### ISSUE THREAD

**Issue by kehh** [wamuseum/providence#133]
![no map tiles](https://cloud.githubusercontent.com/assets/12571/4570254/40787e02-4f5a-11e4-8e4b-694691d199f1.png)
![the tiles](https://cloud.githubusercontent.com/assets/12571/4570253/407392de-4f5a-11e4-8b29-e37729b189f3.png)
![stylechanged](https://cloud.githubusercontent.com/assets/12571/4570252/406aeeea-4f5a-11e4-85de-dfff9f8002f0.png)

**Comment by DannyMurphy** [comment]
Have you fixed this? I cannot reproduce the error.

Can you drop link in the comments to so I can see the same error as you.

I was hope this code would fix it.

`.mapholder img {`
`max-width: auto;`
`}`

**Comment by kehh** [comment]
You can view the maps by using New > Collecting Event.
`.mapholder img {
  max-width: none;
}`
or
`.olMap img {
  max-width: none;
}`
in _olMapSearchLBox.scss fixes this. I'll set up a PR.

**Comment by kehh** [comment]
Fixed by https://github.com/wamuseum/providence/commit/59b9c1c94a3732069fff12d483c10a1207340387
