### ISSUE TITLE
Pulldowns and defaulting to incorrect options when null in source.

### ISSUE THREAD

**Issue by kehh** [wamuseum/providence#142]
In many places if the data exists, it maps to the correct option in the pulldown list. If it does not exist it defaults to the first option in the pulldown list. Would like to be shown how I can correct this (for example, do I just add “Not set” to start of each taxonomy?).

**Comment by kehh** [comment]
As discussed, we need to go through the profile with some code (fix the profile exporter / importer). To fix this in the  Go to the element in the Metadata elements UI and just press save.

**Comment by leftclickben** [comment]
We'll commit the fix to the profile import / export against this issue.

**Comment by mostro20** [comment]
Yep all good, just have to save metadata elements for each area with the "not set" option . Easily managed.
