### ISSUE TITLE
Edit Links jumping out of the way when you click them

### ISSUE THREAD

**Issue by kehh** [wamuseum/providence#148]
in _links.scss:L17 `border: 1px dotted $link;` makes edit links on the admin screens jump out of the way when you click on them. I think if these are in a table or maybe `a.editIcon` don't put the border around them. Couldn't quite bend my head around the sass to do this.
![jumpyeditboxes](https://cloud.githubusercontent.com/assets/12571/5483091/6e324434-86a7-11e4-8449-6b21a52eed9d.png)

**Comment by leftclickben** [comment]
You could use `outline` instead of `border`, it doesn't affect layout.
