### ISSUE TITLE
Update CA codebase to latest upstream

### ISSUE THREAD

**Issue by kehh** [wamuseum/providence#158]
There have been a number of performance improvements in the upstream codebase and it would be good to get these changes deployed onto the museum servers.  We need to schedule this change as it will likely involve some downtime as there is necessary work needed to maintain connection to the LDAP servers. Just filing this as an issue as we need to keep it on our radar.

**Comment by leftclickben** [comment]
From Seth @ Whirl-i-Gig:

> We have a release package for CollectiveAccess 1.5. If you have a bit
> of time to spare could you try installing it and let me know how it
> goes?
> The package is at
> http://www.collectiveaccess.org/sites/default/files/profiles/collectiveaccess-providence-1.5.tgz

**Comment by leftclickben** [comment]
Question from Kehan to Seth:

> That's fantastic news Seth,
> We were busy planning on bringing the Museum's codebase up to the current develop branch as the CA code we have there is stuck in about October last year - it's really great to now be able to base their instance on the master branch (or would you recommend another branch for longer term, more stable releases with bugfixes? master-fix?)
> 
> Thanks to yourself, Stefan and everybody at Whirl-I-Gig for your valiant effort in getting this out the door.

**Comment by leftclickben** [comment]
Reply from Seth:

> Master is what you should be using now. Master-fix will go away soon
> and bug fixes will get pushed into master. We’re also aiming to have
> regular bug fix releases, on the order of once every 8-12 weeks, going
> forward. You know, like regular people do :-)
