### ISSUE TITLE
PHP fatal error when trying to login using web services

### ISSUE THREAD

**Issue by rowead** [wamuseum/providence#221]
I'm getting this error:

```
[Tue Jan 12 11:55:34.153386 2016] [:error] [pid 7333] [client 202.14.152.206:31986] FastCGI: server "/var/lib/apache2/fastcgi/php5.fastcgi" stderr: PHP message: PHP Fatal error:  Call to undefined function mcrypt_create_iv() in /data/cmis/collectiveaccess/providence/20160108093049/app/lib/core/Controller/Request/Session.php on line 156
```

When trying to authenticate using http basic authentication at http://wamcmis-staging.dca.wa.gov.au/service.php/auth/login

I think we just need to include mcrypt support for php. @leftclickben do you have time to look into this? It's not high priority

**Comment by leftclickben** [comment]
I'd say you're right, just need to enable the mcrypt module. I'll take a look.

**Comment by leftclickben** [comment]
I've installed `php5-mcrypt` on staging and restarted php5-fpm, @rowead can you take a look and let me know if working, then I can roll out to production as well.

**Comment by rowead** [comment]
Had to run `php5enmod mcrypt` and restart php5-fpm. @leftclickben hope you don't mind me restarting fpm in the middle of the day, looked safe this morning.

Good to go onto production when you're ready.

**Comment by leftclickben** [comment]
Nope, restart doesn't affect me. Strange that installing the module didn't enable it, I thought they generally did, but okay cool thanks for sorting that. I'll do production later today.

**Comment by leftclickben** [comment]
OK done in production.  I figured as the only active user is currently on maternity leave the restart of `php5-fpm` would be okay.  I'll close this now, please reopen if there are any issues.
